# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'report.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(478, 177)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.dateEdit_begin = QtWidgets.QDateEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dateEdit_begin.setFont(font)
        self.dateEdit_begin.setObjectName("dateEdit_begin")
        self.horizontalLayout_2.addWidget(self.dateEdit_begin)
        self.timeEdit_begin = QtWidgets.QTimeEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.timeEdit_begin.setFont(font)
        self.timeEdit_begin.setObjectName("timeEdit_begin")
        self.horizontalLayout_2.addWidget(self.timeEdit_begin)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.dateEdit_end = QtWidgets.QDateEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dateEdit_end.setFont(font)
        self.dateEdit_end.setObjectName("dateEdit_end")
        self.horizontalLayout_3.addWidget(self.dateEdit_end)
        self.timeEdit_end = QtWidgets.QTimeEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.timeEdit_end.setFont(font)
        self.timeEdit_end.setObjectName("timeEdit_end")
        self.horizontalLayout_3.addWidget(self.timeEdit_end)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_report = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_report.setFont(font)
        self.pushButton_report.setObjectName("pushButton_report")
        self.horizontalLayout_4.addWidget(self.pushButton_report)
        self.pushButton_show = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_show.setFont(font)
        self.pushButton_show.setObjectName("pushButton_show")
        self.horizontalLayout_4.addWidget(self.pushButton_show)
        self.pushButton_quit = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_quit.setFont(font)
        self.pushButton_quit.setObjectName("pushButton_quit")
        self.horizontalLayout_4.addWidget(self.pushButton_quit)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_start_time = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_start_time.setFont(font)
        self.pushButton_start_time.setObjectName("pushButton_start_time")
        self.horizontalLayout.addWidget(self.pushButton_start_time)
        self.pushButton_stop_time = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_stop_time.setFont(font)
        self.pushButton_stop_time.setObjectName("pushButton_stop_time")
        self.horizontalLayout.addWidget(self.pushButton_stop_time)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_5.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "report"))
        self.label.setText(_translate("Form", "Başlangıç"))
        self.label_2.setText(_translate("Form", "Bitiş"))
        self.pushButton_report.setText(_translate("Form", "Rapor"))
        self.pushButton_show.setText(_translate("Form", "Göster"))
        self.pushButton_quit.setText(_translate("Form", "Çıkış"))
        self.pushButton_start_time.setText(_translate("Form", "Start Timer"))
        self.pushButton_stop_time.setText(_translate("Form", "Stop Timer"))

